export const defaultTheme = {
    name:  'defaultTheme',
    color: {
        button: {
            primary:   '#BDBDBD',
            secondary: '#FFEE58',
            error:     'red',
        },
        input: {
            primary:   '#fff',
            secondary: '#FFEE58',
            error:     'red',
        },
        app: {
            primary:   '#006d77',
            secondary: '#83c5be',
        },
        first: {
            primary:        '#5f00a8',
            secondary:      '#7526a6',
            hoverSecondary: '#9338d9',
            containerBg:    '#e3caf5',
        },
        second: {
            primary:          '#1b4332',
            secondary:        '#2d6a4f',
            hoverSecondary:   '#55a630',
            containerBg:      '#d8f3dc',
            anotherSecondary: '#629460',
        },
        third: {
            primary:         '#133c55',
            secondary:       '#386fa4',
            hoverSecondary:  '#59a5d8',
            containerBg:     '#caf0f8',
            locationPrimary: '#415a77',
        },
        fourth: {
            primary:        '#5c4d3c',
            secondary:      '#a56336',
            hoverSecondary: '#f77f00',
            containerBg:    '#f9dcc4',
            typePrimary:    '#a56336',
        },
    },
    fonts: {
        first:      12.15,
        second:     14,
        third:      15,
        fourth:     18,
        fifth:      20,
        sixth:      23,
        seventh:    24,
        eighth:     25,
        ninth:      35,
        tenth:      44,
        eleventh:   72,
        twelfth:    96,
        thirteenth: 100,
    },
};
